apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.asap.im
spec:
  cloudProvider: aws
  kubernetesVersion: "1.29.0"

  api:
    dns: {}
    loadBalancer:
      type: Public

  subnets:
    - name: eu-central-1a
      type: Public
      zone: eu-central-1a
    - name: eu-central-1b
      type: Public
      zone: eu-central-1b

  configStore: s3://asap-kops-state-roman

  topology:
    masters: public
    nodes: public

  networking:
    calico: {}
