apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.asap.im
spec:
  cloudProvider: aws
  kubernetesVersion: "1.29.0"

  networkCIDR: 172.20.0.0/16
  nonMasqueradeCIDR: 100.64.0.0/10

  networking:
    calico: {}

  api:
    loadBalancer:
      type: Public

  kubernetesApiAccess:
    - 0.0.0.0/0

  subnets:
    - name: eu-central-1a
      type: Public
      zone: eu-central-1a

  topology:
    masters: public
    nodes: public

  etcdClusters:
    - name: main
      etcdMembers:
        - name: a
          instanceGroup: master-eu-central-1a

    - name: events
      etcdMembers:
        - name: a
          instanceGroup: master-eu-central-1a
