apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.asap.im
spec:
  cloudProvider: aws
  kubernetesVersion: "1.29.0"

  # DNS для API сервера
  api:
    dns: {}
    loadBalancer:
      type: Public

  # Підмережі (збігаються з AWS region eu-central-1)
  subnets:
    - name: eu-central-1a
      type: Public
      zone: eu-central-1a

  # S3 bucket з Terraform (стан Kops)
  configStore: s3://asap-kops-state-roman

  # Все публічне — найпростіший варіант
  topology:
    masters: public
    nodes: public

  # CNI → Calico (мінімальна конфігурація)
  networking:
    calico: {}

  # etcd — мінімальний, для тестового кластера
  etcdClusters:
    - name: main
      etcdMembers:
        - name: a
          instanceGroup: master-eu-central-1a

    - name: events
      etcdMembers:
        - name: a
          instanceGroup: master-eu-central-1a
