apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.asap.im
spec:
  cloudProvider: aws
  kubernetesVersion: "1.29.0"

  api:
    dns: {}
    loadBalancer:
      type: Public

  subnets:
    - name: eu-central-1a
      type: Public
      zone: eu-central-1a

  configStore: s3://asap-kops-state-roman

  topology:
    masters: public
    nodes: public

  # 🟩 Повністю правильний блок networking
  networking:
    networkCIDR: 172.20.0.0/16
    nonMasqueradeCIDR: 100.64.0.0/10
    calico: {}

  etcdClusters:
    - name: main
      etcdMembers:
        - name: a
          instanceGroup: master-eu-central-1a

    - name: events
      etcdMembers:
        - name: a
          instanceGroup: master-eu-central-1a
