apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
spec:
  role: Node
  image: ami-0f7204385566b32d0
  machineType: t3.small
  minSize: 2
  maxSize: 2
  subnets:
    - eu-central-1a
    - eu-central-1b
